# Generated by Django 5.0.6 on 2024-06-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger_app", "0003_messagelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagelog",
            name="action",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
