# Generated by Django 5.0.6 on 2024-06-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger_app", "0004_messagelog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermessage",
            name="is_system_message",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="системное сообщение"
            ),
        ),
    ]
