# Generated by Django 5.0.6 on 2024-06-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger_app", "0006_userstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstatus",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
